const ALIYA_LABELS = ["ראשון", "שני", "שלישי", "רביעי", "חמישי", "שישי", "שביעי", "מפטיר"];

const PARSHAS = [
  // בראשית
  { he: "בראשית",      api: "Parashat_Bereshit" },
  { he: "נח",          api: "Parashat_Noach" },
  { he: "לך לך",       api: "Parashat_Lech-Lecha" },
  { he: "וירא",        api: "Parashat_Vayera" },
  { he: "חיי שרה",     api: "Parashat_Chayei_Sara" },
  { he: "תולדות",      api: "Parashat_Toldot" },
  { he: "ויצא",        api: "Parashat_Vayetzei" },
  { he: "וישלח",       api: "Parashat_Vayishlach" },
  { he: "וישב",        api: "Parashat_Vayeshev" },
  { he: "מקץ",         api: "Parashat_Miketz" },
  { he: "ויגש",        api: "Parashat_Vayigash" },
  { he: "ויחי",        api: "Parashat_Vayechi" },
  // שמות
  { he: "שמות",        api: "Parashat_Shemot" },
  { he: "וארא",        api: "Parashat_Vaera" },
  { he: "בא",          api: "Parashat_Bo" },
  { he: "בשלח",        api: "Parashat_Beshalach" },
  { he: "יתרו",        api: "Parashat_Yitro" },
  { he: "משפטים",      api: "Parashat_Mishpatim" },
  { he: "תרומה",       api: "Parashat_Terumah" },
  { he: "תצוה",        api: "Parashat_Tetzaveh" },
  { he: "כי תשא",      api: "Parashat_Ki_Tisa" },
  { he: "ויקהל",       api: "Parashat_Vayakhel" },
  { he: "פקודי",       api: "Parashat_Pekudei" },
  // ויקרא
  { he: "ויקרא",       api: "Parashat_Vayikra" },
  { he: "צו",          api: "Parashat_Tzav" },
  { he: "שמיני",       api: "Parashat_Shemini" },
  { he: "תזריע",       api: "Parashat_Tazria" },
  { he: "מצורע",       api: "Parashat_Metzora" },
  { he: "אחרי מות",    api: "Parashat_Achrei_Mot" },
  { he: "קדושים",      api: "Parashat_Kedoshim" },
  { he: "אמור",        api: "Parashat_Emor" },
  { he: "בהר",         api: "Parashat_Behar" },
  { he: "בחקתי",       api: "Parashat_Bechukotai" },
  // במדבר
  { he: "במדבר",       api: "Parashat_Bamidbar" },
  { he: "נשא",         api: "Parashat_Naso" },
  { he: "בהעלתך",      api: "Parashat_Beha'alotcha" },
  { he: "שלח",         api: "Parashat_Sh'lach" },
  { he: "קרח",         api: "Parashat_Korach" },
  { he: "חקת",         api: "Parashat_Chukat" },
  { he: "בלק",         api: "Parashat_Balak" },
  { he: "פינחס",       api: "Parashat_Pinchas" },
  { he: "מטות",        api: "Parashat_Matot" },
  { he: "מסעי",        api: "Parashat_Masei" },
  // דברים
  { he: "דברים",       api: "Parashat_Devarim" },
  { he: "ואתחנן",      api: "Parashat_Vaetchanan" },
  { he: "עקב",         api: "Parashat_Eikev" },
  { he: "ראה",         api: "Parashat_Reeh" },
  { he: "שופטים",      api: "Parashat_Shoftim" },
  { he: "כי תצא",      api: "Parashat_Ki_Teitzei" },
  { he: "כי תבא",      api: "Parashat_Ki_Tavo" },
  { he: "נצבים",       api: "Parashat_Nitzavim" },
  { he: "וילך",        api: "Parashat_Vayeilech" },
  { he: "האזינו",      api: "Parashat_Haazinu" },
  { he: "וזאת הברכה",  api: "Parashat_Vezot_Haberakhah" },
];
